### ISSUE TITLE
Upload button does not work

### ISSUE THREAD

**Issue by danielcrookall** [Lakshya021/cpsc455-project#43]
The upload button on homepage does nothing. The camera icon opens up the document upload as expected.

Fix it so that clicking upload will also open up the document upload.

![image](https://user-images.githubusercontent.com/83941101/177139291-aafdba6e-f581-4079-9792-855f881ef0a7.png)

**Comment by swongg** [comment]
- @danielcrookall  Oops, I will need to write some documentation on how to set-up your local environment so that you guys have access to this feature locally. You will need to register for a google cloud account

Here's a gif of how this works:
![image upload](https://user-images.githubusercontent.com/46267622/177200283-b5450a05-b554-4a12-bbcb-ceb952e27503.gif)
.

**Comment by danielcrookall** [comment]
> * @danielcrookall  Oops, I will need to write some documentation on how to set-up your local environment so that you guys have access to this feature locally. You will need to register for a google cloud account
> 
> Here's a gif of how this works: ![image upload](https://user-images.githubusercontent.com/46267622/177200283-b5450a05-b554-4a12-bbcb-ceb952e27503.gif) [ ](https://user-images.githubusercontent.com/46267622/177200283-b5450a05-b554-4a12-bbcb-ceb952e27503.gif) ![image upload](https://user-images.githubusercontent.com/46267622/177200283-b5450a05-b554-4a12-bbcb-ceb952e27503.gif) [ ](https://user-images.githubusercontent.com/46267622/177200283-b5450a05-b554-4a12-bbcb-ceb952e27503.gif)

Oh nice! I will close this then.
